version: "3.9"
services:

  expressapp:
    container_name: expressapp
    build: ./api
    expose:
      - "4000"
    volumes:
      - ./api:/usr/src/app

  reactapp:
    container_name: reactapp
    build: ./client
    expose:
      - "3000"
    volumes:
      - ./client:/usr/src/app

  nginx:
    container_name: nginx
    build: ./nginx
    expose:
      - "80"
    links:
      - expressapp
      - reactapp
      - nginx-proxy
#      - letsencrypt
    environment:
      - VIRTUAL_HOST=chat.jcoder.es,www.chat.jcoder.es
#      - LETSENCRYPT_HOST=chat.jcoder.es,www.chat.jcoder.es
    restart: always

#  nginx-proxy:
#    container_name: nginx-proxy
#    image: jwilder/nginx-proxy
#    restart: always
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro
#      - certs:/etc/nginx/certs:ro
#      - vhostd:/etc/nginx/vhost.d
#      - html:/usr/share/nginx/html
#    labels:
#      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

#  letsencrypt:
#    container_name: letsencrypt
#    image: jrcs/letsencrypt-nginx-proxy-companion
#    restart: always
#    environment:
#      - NGINX_PROXY_CONTAINER=nginx-proxy
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      - certs:/etc/nginx/certs:rw
#      - vhostd:/etc/nginx/vhost.d
#      - html:/usr/share/nginx/html

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    network_mode: bridge

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=mail@yourdomain.tld
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    network_mode: bridge

volumes:
  certs:
  html:
  vhostd:
  conf:
  acme:
