version: "3.9"

services:

  expressapp:
    container_name: expressapp
    build: ./api
    expose:
      - "4000"
    volumes:
      - ./api:/usr/src/app

  reactapp:
    container_name: reactapp
    build: ./client
    expose:
      - "3000"
    volumes:
      - ./client:/usr/src/app

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    links:
      - expressapp
      - reactapp
      - nginx-proxy
      - letsencrypt
    restart: always
